services:
  gtc-demo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_AZURE_KEY: ${VITE_AZURE_KEY}
        VITE_AZURE_REGION: ${VITE_AZURE_REGION}
        VITE_API_URL: ${VITE_API_URL}
    container_name: gtc_demo
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:80"